spring:
  application:
    name: ticket-reservation

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  sql:
    init:
      mode: always
      data-locations:
        - classpath:db/seed/01_users.sql
        - classpath:db/seed/02_events_tickets.sql

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace